FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# CLUBSPIRE

Get accesss token

## Authentication & Authorization [/token]

### Get accesss token [GET]

+ Response 200 (application/json)

        {
            "access_token": "c1d7200d-26e8-429c-b294-b725ecb4a6ef",
            "token_type": "bearer",
            "refresh_token": "4fac4c0a-c043-41d2-9aa3-3f651656bf97",
            "expires_in": 43199,
            "scope": "write"
        }

+ Response 400 (application/json)

        {
            "error": "invalid_grant",
            "error_description": "Cannot log in user."
        }
        
## Logged user [/users/logged-user]

### Get logged user [GET]

+ Response 200 (application/json)

        {
            "message": {
                "httpStatus": 200,
                "type": "INFO",
                "code": null,
                "clientMessage": null,
                "verboseMessage": null,
                "docUri": null
        },
            "data": [
                {
                    "name": "ClubspireApi",
                    "surname": "ClubspireApi",
                    "phoneCode": "+420",
                    "phone": "123456789",
                    "email": "clubspireapi@api.com ",
                    "streetName": "",
                    "houseNumber": null,
                    "city": "Brno",
                    "zipCode": "12345",
                    "country": "CZ",
                    "woman": true,
                    "note": null,
                    "birthDate": "2016-11-11",
                    "termsAccepted": false,
                    "login": "clubspireapi",
                    "password": null,
                    "passwordAgain": null,
                    "userKey": "870df6b6c0a8020201bcad4e50374009",
                    "lastModifiedDate": "2016-11-30T19:51:21.940+0100"
                }
            ]
        }